# Generated by Django 3.1.6 on 2021-05-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VApp', '0003_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='VolId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='VApp.volunteer'),
        ),
    ]
