# Generated by Django 3.1.6 on 2021-05-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VApp', '0004_item_volid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Sched',
            field=models.TextField(default=''),
        ),
    ]
