# Generated by Django 3.1.6 on 2021-05-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VApp', '0005_item_sched'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='schedT',
            field=models.TextField(default=''),
        ),
    ]
