# Generated by Django 3.1.6 on 2021-06-25 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VApp', '0006_item_schedt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', null=True)),
                ('email', models.TextField(default='', null=True)),
                ('message', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DFood', models.TextField(default='')),
                ('DQuantity', models.IntegerField(default='', null=True)),
                ('DBranch', models.TextField(choices=[('Bayan', 'Bayan'), ('Area 1', 'Area 1'), ('Paliparan 2', ' Paliparan 2')], default='', null=True)),
                ('DSched_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('DStatus', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YTask', models.TextField(default='', null=True)),
                ('YWhen', models.DateTimeField(default='', null=True)),
                ('YWhere', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YName', models.TextField(default='', null=True)),
                ('YAddress', models.TextField(default='', null=True)),
                ('Ybday', models.DateTimeField(default='', null=True)),
                ('YContact', models.CharField(default='', max_length=11)),
                ('YGender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', null=True)),
                ('email', models.TextField(default='', null=True)),
                ('password1', models.TextField(default='', max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='VBranch',
            field=models.TextField(choices=[('Bayan', 'Bayan'), ('Area 1', 'Area 1'), ('Paliparan 2', ' Paliparan 2')], default='', null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='VSched',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='', null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='VSched_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='VStatus',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='VTask',
            field=models.TextField(default='', null=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='profile',
            name='YProfile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='VApp.user'),
        ),
        migrations.AddField(
            model_name='donation',
            name='DoId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='VApp.user'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='VolId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='VApp.user'),
        ),
    ]
